### ISSUE TITLE
strip_tags() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by quadronet** [SSFGizmo/direct_mail#15]
Hey, after clicking the step 3 don´t work:
(1/1) TypeError
strip_tags() expects parameter 1 to be string, null given

typo3conf/ext/direct_mail/Classes/Module/DmailController.php line 1766
` $row['header'] . '<br />' . GeneralUtility::fixed_lgd_cs(strip_tags($row['bodytext']), 200) . '<br /></td>';`

TYPO3 11.5 
PHP 7.4

**Comment by Suprstah** [comment]
Hey quadronet,
got the same issue here. The Problem is an empty "bodytext" – if you're using a picture or headline content element.
I've modified the line 1766 like this:
` $row['header'] . '<br />' . (!empty($row['bodytext']) ? GeneralUtility::fixed_lgd_cs(strip_tags($row['bodytext']), 200): '') . '<br /></td>'; `

**Comment by SSFGizmo** [comment]
fixed https://github.com/SSFGizmo/direct_mail/commit/e73e339c1f988765a7fe411f757b81301b241fff
